Add Japanese locale
markets/jekyll-timeago pull request #31
Opened 2021-01-28 15:47 UTC by jeandeaual

Thanks for the great plugin.

Here is the Japanese translation.

2021-01-28 16:02 UTC, markets commented on lib/locales/ja.yaml
> +zh_hans:
This should be `ja:` :)

2021-01-28 16:02 UTC, markets requested changes
Hi @jeandeaual 👋🏼 and thank you so much for your contribution! Just added a minor comment

2021-01-28 16:04 UTC, jeandeaual commented on lib/locales/ja.yaml
> +zh_hans:
Sorry, fixed 😅

2021-01-28 16:07 UTC, markets approved these changes
Let's wait to CI, but ✅ 

Thanks!

2021-01-29 09:07 UTC, merged

2021-01-30 12:23 UTC, markets commented
@jeandeaual released as `v0.14.0` 🚀 

https://rubygems.org/gems/jekyll-timeago/versions/0.14.0